# Site Information
site_name: cp of smoke 0815
site_url: https://github.com/kikyoo33/itaa-markdown
# site_description: cp of smoke 0815

# # Repository Information
# repo_name: itaa-markdown
# repo_url: https://github.com/kikyoo33/itaa-markdown
# edit_uri: 'edit/main/docs'
docs_dir: 'docs'
# # site_dir: 'site'
# remote_branch: 'gh-pages'
# remote_name: 'origin'

# Server info
# dev_addr: '127.0.0.1:8000'

nav:

  - Table of Content: 

    - 0. Information: index.md

    - 1. Overview: Overview.md

    - 2. Scope: 

      - 2.2 System Context: 

        - 'System Context' : System Context.md

    - 3. Requirement: 

      - 3.1 Use Case Model: 

        - 3.1.1 Use Case Diagram: 

          - 'ucd1' : Use Case Diagram/usecasediagram_Hk5Xbf0ID0c.md

        - 3.1.2 Use Case: 

          - 'uc1' : Use Case/usecase_SyMlWM0LD0q.md

      - 3.2 Functional Requirements: 

        - 'fr1' : Functional Requirements/functionalrequirement_r1p7-GA8wCq.md

    - 4. Data Model: 

      - 4.1 Logical Data Model: 

        - 'erd' : Logical Data Model/logicalerd_HyyEWfRUw09.md

    - 5. Architecture: 

      - 5.1 Architecture Overview: 

        - 5.1.3 IT System View: 

          - 'itsv' : IT System View/aoditsystem_S1xS-MCLPCq.md

          - 'itsv2' : IT System View/aoditsystem_SyCHWfRIPRq.md

        - 5.1.4 Usage Scenario: 

          - 'istsv' : Usage Scenario/aodusagescenario_3wxpM8kNsqb.md

      - 5.2 Architectural Decisions: 

        - 'ad' : Architectural Decisions/architecturaldecision_HJgPWzRLPC9.md

        - 'ad1' : Architectural Decisions/architecturaldecision_BJywbGRIvR5.md

        - 'ad2' : Architectural Decisions/architecturaldecision_BJbP-GRLPC9.md

      - 5.4 Operational Model: 

        - 5.4.1 Logical Operational View: 

          - 'lom1' : Logical Operational View/lomview_r1VDbzRLvAc.md

        - 5.4.2 Prescribed Operational View: 

          - 'pom' : Prescribed Operational View/pomview_ryAPWz08PRc.md


   
       


markdown_extensions:

  - md_in_html

  - toc:

      permalink: True

  - footnotes

  - tables

  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - attr_list

theme:

  name: material
  palette:
    primary: 'black'
    accent: 'red'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  logo: assets/ca.svg
  favicon: assets/ca.svg 
  features:
    # - navigation.tabs
    - navigation.tabs.sticky
  custom_dir:
    theme

extra_css:
  - extra.css
extra_javascript:
  - extra.js